use anyhow::Context as _;
use fs2::FileExt as _;
use std::io::BufRead as _;

/// Represents an active, exclusive lock on a directory.
///
/// This struct guarantees that the process holds an OS-level file lock
/// guarding the specified directory.
pub(crate) struct DirLock {
    /// The path to the directory being guarded.
    pub(crate) path: std::path::PathBuf,
    // Kept alive to hold the flock.
    _file: std::fs::File,
}

impl DirLock {
    /// Acquires an exclusive lock on the specified directory.
    ///
    /// This function blocks until the lock can be acquired. We use a
    /// separate `.lock` file within the directory rather than locking
    /// the directory itself to avoid platform-specific issues with
    /// directory locking and to ensure the lock file persists even if
    /// the directory is cleaned.
    pub(crate) fn lock_exclusive(path: std::path::PathBuf) -> anyhow::Result<Self> {
        let file = Self::open_lock_file(&path)?;
        file.lock_exclusive()
            .with_context(|| format!("Failed to acquire exclusive lock on {:?}", path))?;
        Ok(Self { path, _file: file })
    }

    /// Acquires a shared lock on the specified directory.
    ///
    /// Multiple processes can hold shared locks simultaneously, but an
    /// exclusive lock will block until all shared locks are released.
    pub(crate) fn lock_shared(path: std::path::PathBuf) -> anyhow::Result<Self> {
        let file = Self::open_lock_file(&path)?;
        file.lock_shared()
            .with_context(|| format!("Failed to acquire shared lock on {:?}", path))?;
        Ok(Self { path, _file: file })
    }

    fn open_lock_file(path: &std::path::Path) -> anyhow::Result<std::fs::File> {
        let lock_path = path.join(".lock");

        // Ensure the directory exists.
        if let Some(parent) = lock_path.parent() {
            std::fs::create_dir_all(parent).with_context(|| {
                format!("Failed to create directory for lock file: {:?}", parent)
            })?;
        }
        // If the lock file already exists, we open it in read-only mode.
        // This prevents failures if the file is read-only (e.g., after
        // making the toolchain directory read-only), while still allowing
        // us to acquire shared and exclusive locks on the file descriptor.
        if lock_path.exists() {
            std::fs::OpenOptions::new()
                .read(true)
                .open(&lock_path)
                .with_context(|| format!("Failed to open lock file at {:?}", lock_path))
        } else {
            std::fs::OpenOptions::new()
                .read(true)
                .write(true)
                .create(true)
                .open(&lock_path)
                .with_context(|| format!("Failed to create lock file at {:?}", lock_path))
        }
    }
}

/// Walks a directory recursively and replaces string patterns inside `.trace`
/// files. This is used to patch non-portable paths generated by Lake.
pub(crate) fn patch_trace_files(dir: &std::path::Path, replacements: &[(&str, &str)]) -> anyhow::Result<()> {
    if dir.exists() {
        let walker = walkdir::WalkDir::new(dir).into_iter();
        for entry in walker {
            let entry = entry.context("Failed to walk directory for trace patching")?;
            let path = entry.path();
            if path.is_file() && path.extension().map_or(false, |ext| ext == "trace") {
                let content = std::fs::read_to_string(path)
                    .with_context(|| format!("Failed to read trace file {:?}", path))?;
                let mut new_content = content.clone();
                for (from, to) in replacements {
                    new_content = new_content.replace(from, to);
                }
                if new_content != content {
                    std::fs::write(path, new_content)
                        .with_context(|| format!("Failed to write trace file {:?}", path))?;
                }
            }
        }
    }
    Ok(())
}

/// Prepends a path to an existing environment variable,
/// separating them with a colon if the variable is not empty. This is used
/// to inject our managed Rust toolchain paths before the system paths.
pub(crate) fn prepend_to_env_var(var_name: &str, new_path: &std::path::Path) -> std::ffi::OsString {
    let current_val = std::env::var_os(var_name).unwrap_or_default();
    let mut combined = new_path.to_path_buf().into_os_string();
    if !current_val.is_empty() {
        combined.push(":");
        combined.push(current_val);
    }
    combined
}

/// OS command-line length limits (Windows is ~32k; Linux `ARG_MAX` is
/// usually larger, but variable).
pub(crate) const ARG_CHAR_LIMIT: usize = 32_768;

pub(crate) struct ProcessOutput {
    pub status: std::process::ExitStatus,
    pub stderr_lines: Vec<String>,
}

/// Spawns a child process, drains its stderr in a background thread, and processes
/// its stdout line-by-line in the main thread while showing a progress spinner.
pub(crate) fn run_command_with_progress<F>(
    mut cmd: std::process::Command,
    progress_msg: Option<&str>,
    mut process_stdout_line: F,
) -> anyhow::Result<ProcessOutput>
where
    F: FnMut(&str, Option<&indicatif::ProgressBar>) -> anyhow::Result<()>,
{
    cmd.stdout(std::process::Stdio::piped());
    cmd.stderr(std::process::Stdio::piped());

    let mut child = cmd.spawn().context("Failed to spawn child process")?;

    let stderr_buffer = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));
    let stderr_buffer_clone = std::sync::Arc::clone(&stderr_buffer);

    let mut stderr_thread = None;
    if let Some(stderr) = child.stderr.take() {
        stderr_thread = Some(std::thread::spawn(move || {
            let reader = std::io::BufReader::new(stderr);
            for line in reader.lines().map_while(Result::ok) {
                stderr_buffer_clone.lock().unwrap().push(line);
            }
        }));
    }

    let pb = progress_msg.map(|msg| {
        let pb = indicatif::ProgressBar::new_spinner();
        pb.set_style(
            indicatif::ProgressStyle::default_spinner()
                .template("{spinner:.green} {msg}")
                .unwrap(),
        );
        pb.enable_steady_tick(std::time::Duration::from_millis(100));
        pb.set_message(msg.to_string());
        pb
    });

    if let Some(stdout) = child.stdout.take() {
        let reader = std::io::BufReader::new(stdout);
        for line in reader.lines().map_while(Result::ok) {
            process_stdout_line(&line, pb.as_ref())?;
            if let Some(ref p) = pb {
                p.tick();
            }
        }
    }

    if let Some(ref p) = pb {
        p.finish_and_clear();
    }

    let status = child.wait().context("Failed to wait for child process")?;

    if let Some(thread) = stderr_thread {
        let _ = thread.join();
    }

    let stderr_lines = std::sync::Arc::try_unwrap(stderr_buffer)
        .unwrap()
        .into_inner()
        .unwrap();

    Ok(ProcessOutput { status, stderr_lines })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_prepend_to_env_var() {
        let var_name = "ANNEAL_TEST_VAR";
        unsafe { std::env::remove_var(var_name); }

        // Test when var is empty.
        let path1 = std::path::Path::new("/path/one");
        let res1 = prepend_to_env_var(var_name, path1);
        assert_eq!(res1, "/path/one");

        // Test when var is not empty.
        unsafe { std::env::set_var(var_name, &res1); }
        let path2 = std::path::Path::new("/path/two");
        let res2 = prepend_to_env_var(var_name, path2);
        assert_eq!(res2, "/path/two:/path/one");

        unsafe { std::env::remove_var(var_name); }
    }
}
